name: Bump
on:
  workflow_dispatch:
    inputs:
      strategy:
        description: The strategy to bump the version number
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

defaults:
  run:
    shell: bash -euo pipefail {0}

jobs:
  bump:
    name: Bump
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BUMP_TOKEN }}
      - name: Enable corepack
        run: corepack enable
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: yarn
      - name: Bump version
        run: |
          yarn version "${{ inputs.strategy }}"
          yarn run update-version
          git add package.json updates.json src/manifest.json
      - name: Create tag
        run: |
          version="$(jq -r .version package.json)"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit --message "Bump to $version"
          git tag "$version"
          git push
          git push --tags
