name: CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Enable corepack
        run: corepack enable
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: latest
          cache: yarn
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
