name: CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: yarn
      - name: Enable corepack
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Generate config file
        run: |
          cp ./config.ts.orig ./config.ts
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
